// services listed for the lower pannel.
let household = [
  {
    id: 1,
    Showers: '✔️',
    Laundry: '❌',
    CaseManagement: '✔️',
    FoodBoxes: '❌',
    GasCard: '✔️',
    FoodCard: '❌',
    LifeSkillsClassess: '❌',
    SecurityDeposit: '✔️',
    BusToken: '❌',
    BusPasses: '✔️',
    RentalAssistance: '❌',
    FoodAssistance: '✔️',
    MentalHealth: '❌',
  },
  {
    id: 2,
    Showers: '✔️',
    Laundry: '❌',
    CaseManagement: '✔️',
    FoodBoxes: '❌',
    GasCard: '✔️',
    FoodCard: '❌',
    LifeSkillsClassess: '❌',
    SecurityDeposit: '✔️',
    BusToken: '❌',
    BusPasses: '✔️',
    RentalAssistance: '❌',
    FoodAssistance: '✔️',
    MentalHealth: '❌',
  },
  {
    id: 3,
    Showers: '✔️',
    Laundry: '❌',
    CaseManagement: '✔️',
    FoodBoxes: '❌',
    GasCard: '✔️',
    FoodCard: '❌',
    LifeSkillsClassess: '❌',
    SecurityDeposit: '✔️',
    BusToken: '❌',
    BusPasses: '✔️',
    RentalAssistance: '❌',
    FoodAssistance: '✔️',
    MentalHealth: '❌',
  },
];

export default household;
